apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-felixhub
  labels:
    app: felixhub
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: felixhub
  template:
    metadata:
      labels:
        app: felixhub
    spec:
      
      containers:
        - name: felixhub
          image: "{{ .Values.image.repository | default "feelfeel200088/felixhub.dev" }}:{{ .Values.image.tag | default "latest" }}"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
